/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Normalize a CV file to PDF and optionally compress it.
 *
 * V1 behavior:
 * - If the mime type is a supported image (`image/png`, `image/jpeg`, `image/jpg`),
 *   the image is decoded, optionally downscaled, recompressed as JPEG,
 *   and wrapped into a single-page PDF.
 * - For any other mime type, the input bytes are returned unchanged.
 */
export declare function normalizeCvToPdf(bytes: Uint8Array, mime: string): Array<number>
