/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Normalize a CV file to PDF and optionally compress it.
 *
 * V1 implementation is a no-op: it just echoes back the input bytes.
 * This lets us validate the NAPI-RS wiring and integration from Node/Strapi
 * before implementing the real image/PDF/DOCX pipeline.
 */
export declare function normalizeCvToPdf(bytes: Uint8Array, mime: string): Uint8Array
